Description: >
  Ankush Dadwal / udacity-cloud-devops-capstone
  This template deploys the clusters.


Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: udacity-cloud-devops-capstone


Resources:
  EKSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EKS Cluster Security Group
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Name
          Value: !Sub ${EnvironmentName}-EKSSecurityGroup
      VpcId:
        Fn::ImportValue: udacity-cloud-devops-capstone-VPCID

  EKSSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref EKSSecurityGroup
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId: !Ref EKSSecurityGroup

  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: EKSCluster
      Version: "1.18"
      RoleArn:
        Fn::ImportValue: udacity-cloud-devops-capstone-ClusterRoleArn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref EKSSecurityGroup
        SubnetIds:
          - Fn::ImportValue: udacity-cloud-devops-capstone-PUB1-SN
          - Fn::ImportValue: udacity-cloud-devops-capstone-PUB2-SN

  EKSNodeGroup:
    Type: "AWS::EKS::Nodegroup"
    Properties:
      ClusterName: !Ref EKSCluster
      NodeRole:
        Fn::ImportValue: udacity-cloud-devops-capstone-NodeGroupArn
      ScalingConfig:
        MinSize: 1
        DesiredSize: 1
        MaxSize: 3
      Subnets:
        - Fn::ImportValue: udacity-cloud-devops-capstone-PUB1-SN
        - Fn::ImportValue: udacity-cloud-devops-capstone-PUB2-SN
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Name
          Value: !Sub ${EnvironmentName}-Node


Outputs:

  ClusterArn:
    Description: The EKS Cluster Arn
    Value: !GetAtt EKSCluster.Arn
    Export:
      Name: !Sub "${EnvironmentName}-ClusterArn"

  NodeGroupArn:
    Description: The EKS Node ID
    Value: !GetAtt EKSNodeGroup.Arn
    Export:
      Name: !Sub "${EnvironmentName}-NodeArn"
