version: 2.1


orbs:
  aws-ecr: circleci/aws-ecr@6.15.3


jobs:
  test-backend:
    docker:
      - image: circleci/python:3.9.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd app
            pip install -r requirements.txt
      - run:
          name: test backend
          command: |
            cd app
            pytest


  lint-backend:
    docker:
      - image: circleci/python:3.9.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd app
            pip install -r requirements.txt
      - run:
          name: lint backend
          command: |
            cd app
            flake8 .
            black . --check --exclude="migrations|env"
            isort ./*/*.py --check-only --skip env


  deploy-backend:
    docker:
      - image: jshimko/kube-tools-aws
    steps:
      - checkout
      - run:
          name: deploy backend
          command: |
            aws eks --region ap-northeast-1 update-kubeconfig --name EKSCluster
            kubectl get svc
            # kubectl --kubeconfig ~/.kube/config apply -f kubernetes/deployment.yaml
            # kubectl --kubeconfig ~/.kube/config apply -f kubernetes/loadbalancer.yaml
            # kubectl --kubeconfig ~/.kube/config rollout restart deployment/movies-app


workflows:
  default:
    jobs:
      - test-backend
      - lint-backend
      - aws-ecr/build-and-push-image:
          repo: "udacity-cloud-devops-capstone"
          path: app/
          tag: "${CIRCLE_BRANCH}_${CIRCLE_SHA1},${CIRCLE_BRANCH}_latest"
          requires: [test-backend, lint-backend]
          filters:
            branches:
              only: [main]
      - deploy-backend:
          requires: [aws-ecr/build-and-push-image]
